# Generated by Django 2.0.7 on 2018-07-22 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logradouro', '0001_initial'),
        ('pontos_turisticos', '0002_pontoturistico_atracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='logradouro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logradouro.Logradouro'),
            preserve_default=False,
        ),
    ]
