# Generated by Django 2.0.7 on 2018-07-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=150)),
                ('complemento', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=50)),
            ],
        ),
    ]
